/*
 * Optube User API
 * API description in User optube.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.optube.api;

import com.optube.model.AddNewUserRequest;
import com.optube.model.RetrieveUserInfoRespond;
import com.optube.model.UpdateUserRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserApi
 */
@Ignore
public class UserApiTest {

    private final UserApi api = new UserApi();

    
    /**
     * add a new userd details.
     *
     * add a new userd details.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addNewUserTest() {
        AddNewUserRequest addNewUserRequest = null;
        api.addNewUser(addNewUserRequest);

        // TODO: test validations
    }
    
    /**
     * delete User details.
     *
     * delete User details.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteUserTest() {
        api.deleteUser();

        // TODO: test validations
    }
    
    /**
     * Retrieve user info by userId.
     *
     * Retrieve user info by userId.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUserDetailsTest() {
        String userId = null;
        RetrieveUserInfoRespond response = api.getUserDetails(userId);

        // TODO: test validations
    }
    
    /**
     * update User details.
     *
     * update User details.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateUserTest() {
        UpdateUserRequest updateUserRequest = null;
        api.updateUser(updateUserRequest);

        // TODO: test validations
    }
    
}
