/*
 * Optube User API
 * API description in User optube.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.optube.api;

import com.optube.model.RetrieveUsersInfoByIdsRequest;
import com.optube.model.RetrieveUsersInfosByIdsRespond;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UsersApi
 */
@Ignore
public class UsersApiTest {

    private final UsersApi api = new UsersApi();

    
    /**
     * Retrieve Users Info By Ids.
     *
     * Retrieve Users Info By Ids.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void retrieveUsersInfoByIdsTest() {
        RetrieveUsersInfoByIdsRequest retrieveUsersInfoByIdsRequest = null;
        RetrieveUsersInfosByIdsRespond response = api.retrieveUsersInfoByIds(retrieveUsersInfoByIdsRequest);

        // TODO: test validations
    }
    
}
